Algoritmo "semnome"
// Disciplina   : Algoritmos
// Professor   : Erika
// Autor(a)    : Francisco Antonio dos Santos Correa
// Data atual  : 06/10/2019
Var
// Seção de Declarações das variáveis 
peso, altura, imc: real;


Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreval("Informe o peso: ")
leia (peso)

escreval("informe a altura: ")
leia (altura)

imc <- (peso/(altura*altura))

escreval (" Seu indice de massa corporal é: ", imc)

Fimalgoritmo