Algoritmo "semnome"
// Disciplina   : Algoritmos
// Professor   : Erika
// Autor(a)    : Francisco Antonio dos Santos Correa
// Data atual  : 06/10/2019
Var
// Seção de Declarações das variáveis 
sal_b, sal_r: real;


Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreval("Insira o salario base do funcionário: ")
leia (sal_b)

sal_r <- sal_b - (sal_b*0.065)

escreval (" O salário a receber é: ", sal_r)

Fimalgoritmo