Algoritmo "Questao 6 L2"

Var
Estado : Caracter

Inicio
escreval("insira a sigla do seu estado")
leia(Estado)
se Estado="RJ" entao
escreva("Você é carioca")
fimse
se Estado="SP" entao
escreva("Você é Paulista")
fimse
se Estado="AM" entao
escreva("Você é Amazonense")
fimse
se Estado="PE" entao
escreva("Você é Pernambucano")
fimse
se Estado="BH" entao
escreva("Você é Baiano")
fimse
se Estado="Outro" entao
escreva("Outros Estados")
fimse
Fimalgoritmo